name: "Cloudflare Tunnel"
description: "Cloudflare tunnel to expose the homeassistant"

version: "0.1.0"
url: "https://github.com/fzerorubigd/homeassitant-cf"
image: "fzerorubigd/hass-addon-cf-{arch}"
slug: "cf_tunnel"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  cf_token: "UPDATE-ME"
schema:
  cf_token: str
